import { CategoryMeta, ToolCategory } from './types';

/**
 * 카테고리 메타 정보
 * 새 카테고리 추가 시 여기에 정의
 */
export const CATEGORIES: CategoryMeta[] = [
  {
    id: 'file',
    name_ko: '파일 도구',
    name_en: 'File Tools',
    name_ja: 'ファイルツール',
    name_zh: '文件工具',
    name_es: 'Herramientas de archivo',
    description_ko: 'PDF, 압축, 변환 등',
    description_en: 'PDF, compression, conversion',
    icon: '📁',
    color: 'bg-blue-500',
  },
  {
    id: 'image',
    name_ko: '이미지 도구',
    name_en: 'Image Tools',
    name_ja: '画像ツール',
    name_zh: '图像工具',
    name_es: 'Herramientas de imagen',
    description_ko: '크기 조절, 변환, 편집',
    description_en: 'Resize, convert, edit',
    icon: '🖼️',
    color: 'bg-green-500',
  },
  {
    id: 'qr',
    name_ko: 'QR/바코드',
    name_en: 'QR/Barcode',
    name_ja: 'QR/バーコード',
    name_zh: 'QR/条形码',
    name_es: 'QR/Código de barras',
    description_ko: 'QR 생성, 스캔, 바코드',
    description_en: 'QR generation, scan, barcode',
    icon: '📱',
    color: 'bg-purple-500',
  },
  {
    id: 'text',
    name_ko: '텍스트 도구',
    name_en: 'Text Tools',
    name_ja: 'テキストツール',
    name_zh: '文本工具',
    name_es: 'Herramientas de texto',
    description_ko: '글자 수, 변환, 비교',
    description_en: 'Character count, convert, compare',
    icon: '📝',
    color: 'bg-yellow-500',
  },
  {
    id: 'calc',
    name_ko: '계산/변환',
    name_en: 'Calculate/Convert',
    name_ja: '計算/変換',
    name_zh: '计算/转换',
    name_es: 'Calcular/Convertir',
    description_ko: '단위 변환, 계산기',
    description_en: 'Unit conversion, calculator',
    icon: '🔢',
    color: 'bg-red-500',
  },
  {
    id: 'life',
    name_ko: '생활 도구',
    name_en: 'Life Tools',
    name_ja: '生活ツール',
    name_zh: '生活工具',
    name_es: 'Herramientas de vida',
    description_ko: '날씨, 시간, 일정',
    description_en: 'Weather, time, schedule',
    icon: '🏠',
    color: 'bg-teal-500',
  },
  {
    id: 'fun',
    name_ko: '재미/놀이',
    name_en: 'Fun/Games',
    name_ja: '楽しい/ゲーム',
    name_zh: '趣味/游戏',
    name_es: 'Diversión/Juegos',
    description_ko: '랜덤, 게임, 뽑기',
    description_en: 'Random, games, picker',
    icon: '🎮',
    color: 'bg-pink-500',
  },
  {
    id: 'finance',
    name_ko: '금융 계산기',
    name_en: 'Finance Calculator',
    name_ja: '金融計算機',
    name_zh: '金融计算器',
    name_es: 'Calculadora financiera',
    description_ko: '연봉, 이자, 세금 계산',
    description_en: 'Salary, interest, tax calculation',
    icon: '💰',
    color: 'bg-emerald-500',
  },
  {
    id: 'health',
    name_ko: '건강/반려동물',
    name_en: 'Health/Pets',
    name_ja: '健康/ペット',
    name_zh: '健康/宠物',
    name_es: 'Salud/Mascotas',
    description_ko: 'BMI, 칼로리 계산',
    description_en: 'BMI, calorie calculation',
    icon: '🏥',
    color: 'bg-rose-500',
  },
  {
    id: 'video',
    name_ko: '영상 도구',
    name_en: 'Video Tools',
    name_ja: 'ビデオツール',
    name_zh: '视频工具',
    name_es: 'Herramientas de video',
    description_ko: '영상 변환, 편집, 추출',
    description_en: 'Video conversion, edit, extract',
    icon: '🎥',
    color: 'bg-cyan-500',
  },
];

/**
 * 카테고리 ID로 메타 정보 조회
 */
export function getCategoryMeta(id: ToolCategory): CategoryMeta | undefined {
  return CATEGORIES.find(cat => cat.id === id);
}
